blog/Blog/Blog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token
from main.api import viewsets

router = routers.DefaultRouter()
router.register(r'blog', viewsets.PostViewSet)
router.register(r'category', viewsets.CategoriaViewSet)
router.register(r'indicacao', viewsets.IndicacaoViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/', include(router.urls)),
    path('api-token-auth/', obtain_auth_token),
    path('', include('main.urls', namespace = 'main')),
    path('user/', include('usuarios.urls', namespace = 'usuarios')),
    path('social/', include('social.urls', namespace = 'social')),
    path('social-auth/', include('social_django.urls', namespace='social-auth')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)


admin.site.site_header = 'Infocode'
admin.site.site_title = 'Mantenha-se conectado com todas tecnologias'
admin.site.site_header = 'Sistema de gerenciamento da infocode'

blog/Blog/social/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from django.views.static import serve

from django.urls import path, include
from . import views
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

app_name = 'social'

urlpatterns = [
    # Url do Feed, onde mostra todas publicações feitas
    path('feed', views.feed, name='feed'), 
    # Url para deletar POST escolhido pelo usuário, utilizamos a ID para fazer a seleção do POST
    path('deletar-post/<str:id>/', views.deletarPublicacao, name='deletar-post'),
    # Url para editar POST escolhido pelo usuário
    path('editar-post/<str:id>/', views.editarPublicacao, name='editar-post'),
    # Url para comentar POST escolhido pelo usuário
    path('comentar_post/<str:id>/', views.comentar_Publicacao, name='comentar_post'),
    # Url para ver POST completo(comentários) escolhido pelo usuário
    path('usuarios/', views.usuarios, name='usuarios'),

    path('like/', views.like_post, name='like_post'),
    
]

blog/Blog/usuarios/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from django.views.static import serve

from django.urls import path, include
from . import views
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

app_name = 'usuarios'

urlpatterns = [
    # View com formulário de cadastro de usuários
    path('cadastro', views.CadastroFormView.as_view(), name='cadastro'),
    # View que redireciona após o sucesso de cadastro
    path('cadastro/sucess', views.RegistradoView.as_view(), name='sucess'),
    # View de perfil do usuário
    path('profile/<int:pk>', views.ProfileView, name='profile'),  
    # View para editar informações de usuários
    path('edit/<int:pk>', views.UserChange.as_view(), name='edit'),

    path('seguir/<int:id>', views.seguir_usuario, name = 'seguir')

]           

blog/Blog/social/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.fields.related import ForeignKey
from usuarios.models import CustomUser

import uuid

# Modelo de Publicação
# Estamos importando o Custom User para autenticar o usuário
class Publicacao(models.Model):
    usuario = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    conteudo = models.TextField()
    data = models.DateTimeField(auto_now_add= True)
    foto = models.ImageField(null = True, blank = True,  upload_to="static/img/")
    liked = models.ManyToManyField(User,default=None,blank=True,related_name='LIked')
    
    class Meta:
        verbose_name = 'Publicação'
        verbose_name_plural = 'Publicações'
        ordering = ['-data']

    def __str__(self):
        return self.usuario.first_name

    @property
    def num_likes(self):
        return self.liked.all().count()

LIKE_CHOICES = (
    ('l','Like'),
    ('d','Deslike'),
)

class Like(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    post = models.ForeignKey(Publicacao,on_delete=models.CASCADE)
    value = models.CharField(choices=LIKE_CHOICES,default='Like',max_length=10)


class Comment(models.Model):
    usuario = models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    publicacao = models.ForeignKey(Publicacao,on_delete=models.CASCADE)
    comentario = models.TextField(null=True,blank=True)
    criacao = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4,unique=True,primary_key=True,editable=False)

    def __str__(self):
        return self.comentario

    class Meta:
        verbose_name = 'Comentario'
        verbose_name_plural = 'Comentários'
        ordering = ['-criacao']

blog/Blog/usuarios/models.py
# from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
from django.db.models.fields import CharField
from localflavor.br.models import BRStateField, BRPostalCodeField
from django.contrib.auth.models import User

# Model de usuário
# BRStateField e BRPostalCodeField são importações de uma biblioteca chamada localFlavor para UF e CEP

class CustomUser(User):
    telefone = models.CharField(max_length=15, null=True, blank=True)
    aniversario = models.DateField(auto_now_add=False, null=True, blank=True)
    foto = models.ImageField(null=True, blank=True, upload_to="static/img/")
    estado = BRStateField(null = True, blank = True)
    CEP = BRPostalCodeField(null = True, blank = True)
    cidade = models.CharField(max_length=155, null=True)
    genero_choices = [("F", "Feminino"), ("H", "Masculino"), ("O", "Outro")]
    genero = models.CharField(choices=genero_choices, default="M", max_length=1)
    link_fb = models.CharField(null=True, blank=True, max_length=255)
    link_git = models.CharField(null=True, blank=True, max_length=255)
    link_tt = models.CharField(null=True, blank=True, max_length=255)
    link_ig = models.CharField(null=True, blank=True, max_length=255)
    seguidores = models.ManyToManyField(User, related_name='seguidores')

    ocupacao_choices = [
        ('Estudante', 'Estudante'), ('Trabalha na área', 'Trabalha na área')
        ]
    ocupacao = models.CharField(max_length=20, choices= ocupacao_choices, default='Estudante')
    

    def __str__(self):
        return self.first_name





# class Seguir(models.Model):
#     user = models.OneToOneField(User,null=True ,blank=True,related_name='seguidor',on_delete=models.CASCADE)

#     def __str__(self):
#         return str(self.user)

blog/Blog/social/forms.py
from django import forms
from .models import Comment, Publicacao


# Formulário de publicação, onde é solicitado o conteúdo e caso o usuário queira, uma foto
class Publicacao_form(forms.ModelForm):

    class Meta:
        model = Publicacao

        widgets = {
            'conteudo': forms.Textarea(attrs={'placeholder': 'Escreva algo', 'id': 'editor'}),
        }
        fields = ('conteudo', 'foto')
        labels = {'conteudo': '', 'foto': ''}

# Form de comentário na publicação
class Comentario_publi(forms.ModelForm):
    class Meta:
        model = Comment
        fields = {'comentario'}
        # widgets = {
        #     'comentario': forms.Textarea(attrs={'placeholder': 'Faça um comentário..'}),
        # }
        labels = {'comentario':'comentario'}

        

blog/Blog/usuarios/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model
from .models import CustomUser
from django import forms

# Formulário para cadastrar usuário

class UsuarioForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ('username','first_name', 'last_name', 'email')
        labels = {'username': 'Usuário'}
# Formulário para editar informações do usuário

class UsuarioFormChange(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('first_name', 'last_name', 'email', 'telefone', 'estado','cidade', 'ocupacao', 'genero', 'CEP', 'link_fb', 'link_tt', 'link_ig', 'link_git', 'foto')
        labels = {'link_fb': 'Facebook', 'link_tt':'Twitter', 'link_ig': 'Instagram', 'link_git':'Github'}

        def save(self, commit= True):
            user =  super().save(commit=False)    
            if commit:
                user.save()
            return user

blog/Blog/social/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse, request, response
from django.views import generic
from .models import Publicacao,Like
from django.shortcuts import  get_list_or_404
from django.urls.base import reverse_lazy
from .forms import Publicacao_form,Comentario_publi
from usuarios.models import CustomUser
from .models import Comment
from random import choices

# View feed, passamos o formulário de Publicação
# Data - passamos o model de Publicação
# Form - Passamos o formulário de Publicação
def feed(request):
    posts = Publicacao.objects.all()
    comentarios = Comment.objects.filter()
    
    
    if request.method == 'POST':
       form = Publicacao_form(request.POST)
       if form.is_valid():
           data = Publicacao()
           data.conteudo = form.cleaned_data['conteudo']
           data.foto = form.cleaned_data['foto']
           data.usuario_id = request.user.id
           data.save()
           return redirect("social:feed")
    else:
        form = Publicacao_form()
    context = {"posts":posts, "form":form,'comentarios':comentarios, 'usuarios':usuarios }
    return render (request, "social/feed.html", context)


def usuarios(request):
    usuarios = get_list_or_404(CustomUser)
    context = {'usuarios':usuarios }
    return render (request, "social/usuarios.html", context)
# View para o usuário comentar alguma publicação
# Redireciona ele para uma página e quando ele realizar o comentário, volta para o FEED
# Data - Passamos o model Comentário
def comentar_Publicacao(request, id):
    post = Publicacao.objects.get(id = id)
    if request.method == 'POST':
        form_comentario = Comentario_publi(request.POST)
        if form_comentario.is_valid():
            data = Comment()
            data.comentario = form_comentario.cleaned_data['comentario']
            # data.foto = form_comentario.cleaned_data['foto']
            data.usuario_id = request.user.id
            data.publicacao_id = post.id
            data.save()
            return redirect("social:feed")
    else:
        form_comentario = Comentario_publi()
    context = {'post':post,"form_comentario":form_comentario}
    return render(request,'social/comentar_post.html',context)

# Função para deletar publicação, redireciona o usuário para uma página onde ele pode deletar a publicação
def deletarPublicacao(request,id):
    post = Publicacao.objects.get(id=id)
    if request.method == 'POST':
        post.delete()
        return redirect("social:feed")

    context = {'post':post}
    return render(request,'social/deletar-post.html',context)

# Função para editar publicação, redireciona o usuário para uma página onde ele pode editar a publicação
# No form, está instanciado a publicação anterior e o usuário pode editar
def editarPublicacao(request,id):
    post = Publicacao.objects.get(id=id)
    form = Publicacao_form(instance=post)
    if request.method == 'POST':
        form = Publicacao_form(request.POST,instance=post)
        form.save()
        return redirect("social:feed")

    context = {'post':post,'form':form}
    return render(request,'social/editar-post.html',context)

def like_post(request):
    user = request.user
    if request.method == 'POST':
        post_id = request.POST.get('post_id')
        post_obj = Publicacao.objects.get(id=post_id)
        
        if user in post_obj.liked.all():
            post_obj.liked.remove(user)
        else:
            post_obj.liked.add(user)

        like , created = Like.objects.get_or_create(user=user,post_id=post_id)

        if not created:
            if like.value =='Like':
                like.value = 'Deslike'

            else:
                like.value = 'Like'

            like.save()

    return redirect("social:feed")

blog/Blog/usuarios/views.py
from .models import CustomUser
from django.db.models.base import Model
from django.shortcuts import  get_list_or_404, render, redirect, get_object_or_404
from django.urls.base import reverse_lazy
from django.views import generic
from django.views.generic.edit import FormView
from .forms import UsuarioForm, UsuarioFormChange
from Contato.enviar_email import enviar_email_via_gmail
from social.models import Publicacao
from django.contrib.auth.models import User
from django.http import HttpResponse


 
#  View para cadastrar os usuários
class CadastroFormView(generic.CreateView):
    form_class = UsuarioForm
    template_name = "registration/cadastro.html"
    success_url = reverse_lazy("usuarios:sucess")

# View que redireciona para página de sucesso no cadastro
class RegistradoView(generic.TemplateView):
    template_name = "registration/sucess.html"

# View do perfil de usuário, pk seria o id do user
def ProfileView(request, pk):
    usuario = CustomUser.objects.get(pk=pk)
    email = usuario.email   
    enviar_email_via_gmail('Bem-vindo à InfoCode', "teste", email)
    
    return render (request, "registration/profile.html", { "user": usuario})

# View para editar informações do usuário
class UserChange(generic.UpdateView):
    model = CustomUser
    form_class = UsuarioFormChange
    template_name = 'registration/edit_user.html'
    success_url = reverse_lazy("social:feed")
    

def seguir_usuario(request, id):
    request.user.seguidores.add(get_object_or_404(CustomUser, id=id))
    return redirect("social:feed")




    

blog/Blog/templates/social/comentar_post.html
{% extends 'base_social.html' %} {% load static %} {% load crispy_forms_tags %} {% block main %}


<form action='{% url "social:comentar_post" post.id  %}' method="POST">
    <div>
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="staticBackdropLabel">Faça um comentário</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
                </div>
                <div class="modal-body">
                    <form method="post" action="">
                        {% csrf_token %}
                        <div class="input-group">
                            {{ form_comentario.comentario|as_crispy_field }}

                        </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-success" type="submit" name="post">Comentar</button>
                    <a role="button" class="btn btn-success" href='{% url "social:feed"   %}'>Voltar</a>
                </div>
                </form>
            </div>
        </div>
    </div>


</form>

 {%endblock%}

blog/Blog/templates/social/deletar-post.html
{% extends 'base_social.html' %} {% load static %} {% load crispy_forms_tags %} {% block main %}
<div class="container-sm text-center" style="padding: 50px">
    <p>Tem certeza que deseja excluir essa publicação?</p>

    <form action='{% url "social:deletar-post" post.id  %}' method="POST">
        {% csrf_token %}

        <button class="btn-success btn" type="submit">Deletar</button>
        <a href='{% url "social:feed"   %}'>
            <button class="btn-success btn" type="submit">Voltar</button></a>
    </form>
</div>

{% endblock %}

blog/Blog/templates/social/editar-post.html
{% extends 'base_social.html' %} {% load static %} {% load crispy_forms_tags %} {% block main %}


<div class="container-sm" style="padding: 50px;">
    <h4>Alterar Publicação</h4>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            {{ form.conteudo|as_crispy_field }}
        </div>
        <div class="form-group">
            {{ form.foto|as_crispy_field }}
        </div>
        <div class="form-group">
            <button class="btn btn-success" type="submit" name="post">Salvar alterações</button>
        </div>

    </form>
    <form method="post" action="">

        <div class="input-group">


        </div>
</div>




{% endblock %}

blog/Blog/templates/social/feed.html
{% extends 'base_social.html' %} {% load static %} {% load crispy_forms_tags %} {%block main%} {% if request.user.is_authenticated %}


<!-- Section formulário de publicação -->
<section class="hero">
    <div class="container">
        <div class="row">

            <div class="col-lg-6 offset-lg-3">
                <div class="cardbox shadow-lg bg-white">
                    <div class="cardbox-heading">
                        <div class="media m-0">
                            <div class="d-flex mr-3">
                                <a href="#"><img class="img-fluid rounded-circle" src="{%static 'img/teste.png' %}" alt="{{user.user}}"></a>
                            </div>
                            <!--d-flex-->
                            <div class="media-body">
                                <!-- Button trigger modal -->
                                <button type="button" class="btn btn-outline-success" data-toggle="modal" data-target="#staticBackdrop">
          Faça uma publicação</button>
                                <!-- Modal -->
                                <div class="modal fade" id="staticBackdrop" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="staticBackdropLabel">Crie uma Publicação</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
                                            </div>
                                            <!--modal-header-->

                                            <div class="modal-body">
                                                <form method="POST" enctype="multipart/form-data">
                                                    {% csrf_token %} {{ form.conteudo|as_crispy_field }} {{ form.foto|as_crispy_field }}
                                                    <div class="modal-footer">
                                                        <input class="btn btn-success" type="submit" value="Salvar">
                                                    </div>
                                                    <!--modal footer-->
                                                </form>
                                            </div>
                                            <!--modal body-->
                                        </div>
                                        <!--modal-content-->
                                    </div>
                                    <!--modal dialog-->
                                </div>
                                <!--modal-->
                            </div>
                            <!--media-body-->
                        </div>
                        <!--media-->
                    </div>
                    <!--/ cardbox-heading -->
                </div>
                <!--cardbox shadow-lg bg-white -->
            </div>
            <!--col-lg-6 offset-lg-3-->
        </div>
        <!--/ row -->
    </div>
    <!--/ container -->
</section>
<!--Hero-->



<!-- Todos os posts que foram feitos -->

<section style="padding: 1px;" class="hero">

    
    {%for post in posts%}
    <div class="container">
        <div class="row">

            <div class="col-lg-6 offset-lg-3">

                <div class="cardbox shadow-lg bg-white">

                    <div class="cardbox-heading" style="border-bottom: 1px solid #ccc;">

                        <div class="media m-0">

                            <div class="d-flex mr-3">
                                {%if post.usuario.foto%}
                                <a href="#"><img class="img-fluid rounded-circle" src="{{post.usuario.foto.url}}" alt="{{post.usuario}}"></a>
                                {%else%}
                                <img class="img-fluid rounded-circle" src="{%static 'img/teste.png' %}" alt="" srcset=""> {%endif%}
                            </div>
                            <div class="media-body">
                                <span class="m-0"> <a href='{% url "usuarios:profile" post.usuario.id%}'>{{post.usuario}}</a> </span>
                                <small><p><i class="icon ion-md-time"></i>{{post.data}}</p></small>
                            </div>
                            <div class="dropdown mr-1">
                                <span class="d-flex justify-content-end dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  ...
                </span>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                    <a class="dropdown-item" href="{% url 'social:editar-post' post.id %} ">Editar</a>
                                    <a class="dropdown-item" href="{% url 'social:deletar-post' post.id %}">Excluir</a>

                                </div>
                            </div>
                        </div>
                        <!--/ media -->
                    </div>
                    <!--/ cardbox-heading -->
                    <div class="cardbox-item" style="padding: 10px;">
                        <p class="card-text">{{post.conteudo|linebreaks}} </p>
                    </div>
                    <!--/ cardbox-item -->

                    {% if post.foto %}
                    <div class="cardbox-item">
                        <img class="img-fluid" src="{{post.foto.url}}" alt="Image">
                    </div>
                    <!--/ cardbox-item -->
                    {%endif%}
                    <div class="cardbox-item" style="padding: 10px;">
                        <div class="container d-flex">
                            <form action="{% url 'social:like_post' %}" method='POST'>
                                {% csrf_token %}
                                <input type="hidden" name="post_id" value="{{post.id}}"> {% if user not in post.liked.all %}
                                <a href=""><button style="border: 1px solid black;" class="btn btn-light" type="submit"><i class="bi bi-heart-fill"></i></button></a> {% else %}
                                <a href=""><button type="submit" class=" btn-success align-items-center btn"><i class="bi bi-heart-fill"></i></button></a> {% endif %}
                            </form>
                            <span style="margin-left: 5px;">              
                      <a class="btn btn-outline-success" role="button" href="{%url 'social:comentar_post' post.id%}">Comentar</a></button>
                  </span>
                            <span>
                    <a class="btn btn-success" style="margin-left: 5px;" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
                    Comentários
                    </a>
                  </span>
                        </div>
                        <!--container dflex-->
                        <small style="padding: 20px;">{{post.liked.all.count}} Curtida{{post.liked.all.count|pluralize:"s"}} </small>
                    </div>
                    <!--cardbox-->
                </div>
                <!--cardbox shadow-lg-->

                {% for comment in post.comment_set.all %}

                <div class="collapse comment__details" id="collapseExample" style="margin-bottom: 10px;">
                    <div class="card card-body" style="height: 140px;">
                        <div class="cardbox-heading">

                            <div class="media m-0">

                                <div class="d-flex mr-3">
                                    {%if comment.usuario.foto%}
                                    <a href="#"><img class="img-fluid rounded-circle" src="{{comment.usuario.foto.url}}" alt="{{comment.usuario}}"></a>
                                    {%else%}
                                    <img class="img-fluid rounded-circle" src="{%static 'img/teste.png' %}" alt="" srcset=""> {%endif%}
                                </div>
                                <div class="media-body">
                                    <span class="m-0"> <a href="{% url 'usuarios:profile' comment.usuario.id%}">{{comment.usuario}}</a> </span>
                                    <small><p><i class="icon ion-md-time"></i>{{comment.criacao}}</p></small>
                                </div>

                            </div>
                            <!--/ media -->
                        </div>
                        <!--/ cardbox-heading -->
                        <div class="cardbox-item">
                            <p class="card-text">{{comment.comentario|linebreaks}} </p>
                        </div>
                        <!--/ cardbox-item -->


                    </div>
                    <!--card-->
                </div>
                <!--collapse-->
                {% endfor %}

            </div>
            <!--/ col-lg-6 offset-lg-3 -->
        </div>
        <!--/ row -->
    </div>
    <!--/ container -->


</section>
{%endfor%} {%endif%} {%endblock%}

blog/Blog/templates/social/usuarios.html
{% extends 'base_social.html' %} {% load static %} {% load crispy_forms_tags %} {%block main%}

<div class="container">
    
    
    {%for user in usuarios%}
      <div class="col mb-4"style = "padding:20px">
        <div class="card">
          <div class="media m-0"  style="border-bottom: 1px solid #ccc; padding: 10px;">
              <div class="d-flex mr-3"> 
                {%if user.foto%}         
                  <a href="#"><img class="img-fluid rounded-circle" src="{{user.foto.url}}" alt=""></a>  
                {%endif%}            
              </div>
              <div class="media-body">
                  <span class="m-0"> <a href="{% url 'usuarios:profile' user.id%}">{{user.get_full_name}}</a> </span>
                  <small><p><i class="icon ion-md-time"></i>{{user.ocupacao}}</p></small>
              </div>
          </div>
          <div class="card-body">
            <small class="card-text"></i>{{user.cidade}}</small>,
            <small class="card-text"></i>{{user.estado}}</small>
          </div>
          <div class="card-footer">
            <a href="{% url 'usuarios:profile' user.id%}" role="alert">Ver perfil</a>
          </div>
        </div>
      </div>
      {%endfor%}
    </div>


{%endblock%}