blog/Blog/Blog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token
from main.api import viewsets

router = routers.DefaultRouter()
router.register(r'blog', viewsets.PostViewSet)
router.register(r'category', viewsets.CategoriaViewSet)
router.register(r'indicacao', viewsets.IndicacaoViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/', include(router.urls)),
    path('api-token-auth/', obtain_auth_token),
    path('', include('main.urls', namespace = 'main')),
    path('user/', include('usuarios.urls', namespace = 'usuarios')),
    path('social/', include('social.urls', namespace = 'social')),
    path('social-auth/', include('social_django.urls', namespace='social-auth')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)


admin.site.site_header = 'Infocode'
admin.site.site_title = 'Mantenha-se conectado com todas tecnologias'
admin.site.site_header = 'Sistema de gerenciamento da infocode'

blog/Blog/main/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from django.views.static import serve

from django.urls import path, include
from . import views
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

app_name = 'main'

urlpatterns = [
    # Url principal do blog
    path('', views.home, name = 'post'),
    # Url que redireciona para um artigo especificio pelo ID
    path('<int:pk>/', views.PostDetailView, name='post_detail'),
    # Url que redireciona para nossas indicações de livros e cursos
    path('indicacao/', views.indicacao, name='indicacao'),
    # Url que redireciona para uma indicação especificia pelo ID
    path('indicacao/<int:pk>/', views.IndicacaoDetailView.as_view(), name='indicacao_detail'),
    path('contato', views.Contato_view.as_view(), name='contato'),

    path('curtir/', views.curtir_post, name='curtir_post'),
]

blog/Blog/usuarios/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from django.views.static import serve

from django.urls import path, include
from . import views
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

app_name = 'usuarios'

urlpatterns = [
    # View com formulário de cadastro de usuários
    path('cadastro', views.CadastroFormView.as_view(), name='cadastro'),
    # View que redireciona após o sucesso de cadastro
    path('cadastro/sucess', views.RegistradoView.as_view(), name='sucess'),
    # View de perfil do usuário
    path('profile/<int:pk>', views.ProfileView, name='profile'),  
    # View para editar informações de usuários
    path('edit/<int:pk>', views.UserChange.as_view(), name='edit'),

    path('seguir/<int:id>', views.seguir_usuario, name = 'seguir')

]           

blog/Blog/Contato/models.py
from django.db import models


class Contato(models.Model):
    email = models.EmailField()
    assunto = models.CharField(max_length=255)
    mensagem = models.TextField()

    def __str__(self):
        return self.email

blog/Blog/main/models.py
from ckeditor.fields import RichTextField
from django.db import models
from django.conf import settings
from django.db.models.deletion import CASCADE
from django.db.models.fields.related import ManyToManyField
from usuarios.models import CustomUser
from django.contrib.auth.models import User
import uuid

# Model para cadastrarmos as categorias dos artigos

class Categoria(models.Model):
    categoria = models.CharField(max_length=100)

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'

    def __str__(self):
        return self.categoria

# Model de Publicações, onde colocamos conteúdos, títulos e etc

class Post(models.Model):
    categoria = models.ManyToManyField(Categoria)
    titulo = models.CharField(max_length=1000)
    subtitulo = models.CharField(max_length=1000,null=True, blank=True)
    conteúdo = models.TextField()
    criado_por = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete= models.CASCADE)
    criado_em = models.DateField(auto_now_add= False)
    foto = models.ImageField(null=True, blank=True, upload_to="static/img/")
    curtidas = models.ManyToManyField(User, default=None,blank=True,related_name='Curtidas')
    
    @property
    def num_curtidas(self):
        return self.curtidas.all().count()

    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'
        ordering = ['-criado_em']


    def __str__(self):
        return self.titulo

CURTIR_CHOICES=(
    ('g','Gostei'),
    ('n','Não Gostei'),
)

class Curtir(models.Model):
    usuario = models.ForeignKey(User,on_delete=models.CASCADE)
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    avaliacao = models.CharField(choices=CURTIR_CHOICES,default='Gostei',max_length=10)

    def __str__(self):
        return str(self.post)

# Model onde indicamos livros e Cursos

class Indicacao(models.Model):
    INDICACAO_CHOICES = [
        ('l', 'Livro'), ('c', 'Curso')
    ]
    indicacao = models.CharField(max_length=10, choices= INDICACAO_CHOICES, default='curso')
    titulo = models.CharField(max_length=100)
    categoria = models.ForeignKey(Categoria, on_delete= models.CASCADE)
    autor = models.CharField(max_length=100)
    sinopse = RichTextField()
    link = models.CharField(max_length=2000,null=True,blank=True)
    criado_em = models.DateField(auto_now_add= False)
    foto = models.FileField(null=True, blank=True, upload_to="static/img/")

    class Meta:
        verbose_name = 'Indicação'
        verbose_name_plural = 'Indicações'

    def __str__(self):
        return self.titulo

# Models para os usuários deixarem comentários nos artigos

class Comentarios(models.Model):
    usuario=models.ForeignKey(CustomUser,on_delete=models.CASCADE, null=True)
    email =models.CharField(max_length=255, null=True)
    post = models.ForeignKey(Post, on_delete = models.CASCADE, related_name ='comentarios')
    comentario = models.TextField()
    data = models.DateTimeField(null=True , auto_now_add=True)
    aprovado = models.BooleanField(default=True)
    

    class Meta:
        verbose_name = 'Comentário'
        verbose_name_plural = 'Comentários'

    def __str__(self):
        return self.usuario.first_name


class Reviews(models.Model):
    usuario = models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    publicacao = models.ForeignKey(Post,on_delete=models.CASCADE)
    comentario = models.TextField(null=True,blank=True)
    criacao = models.DateTimeField(auto_now_add=True)
    

    def __str__(self):
        return self.comentario


# class Comment(models.Model):
#     usuario = models.ForeignKey(CustomUser,on_delete=models.CASCADE)
#     publicacao = models.ForeignKey(Publicacao,on_delete=models.CASCADE)
#     comentario = models.TextField(null=True,blank=True)
#     criacao = models.DateTimeField(auto_now_add=True)
#     id = models.UUIDField(default=uuid.uuid4,unique=True,primary_key=True,editable=False)

#     def __str__(self):
#         return self.comentario

blog/Blog/Contato/forms.py
from django.forms import ModelForm
from .models import Contact


class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

blog/Blog/templates/blog/contato.html
{% extends "base.html" %} {% load static %} {% block title %}Infocode | Contato{% endblock %} {% block main %}


<div class="container">
    <h1 style="padding: 25px;" class="text-center">Entre em contato com nossa equipe</h1>

    <div class="row row-cols-1 row-cols-md-2">
        <div class="col mb-4">
          <div class="card">
            <div class="media m-0"  style="border-bottom: 1px solid #ccc; padding: 10px;">
                <div class="d-flex mr-3">               
                    <a href="#"><img class="img-fluid rounded-circle" src="{%static 'img/antonio.jfif'%}" alt=""></a>              
                </div>
                <div class="media-body">
                    <span class="m-0"> <a href="">Antonio Bruno Kremer Lamim</a> </span>
                    <small><p><i class="icon ion-md-time"></i>Desenvolvedor</p></small>
                </div>
            </div>
            <div class="card-body">
              <small class="card-text"><i style="padding: 5px;" class="bi bi-envelope"></i>brunokremer022@gmail.com</small>|
              <small class="card-text"><i style="padding: 5px;" class="bi bi-telephone-fill"></i>+55 (47) 9 99033958</small>
            </div>
          </div>
        </div>

        <div class="col mb-4">
            <div class="card">
              <div class="media m-0"  style="border-bottom: 1px solid #ccc; padding: 10px;">
                  <div class="d-flex mr-3">               
                      <a href="#"><img class="img-fluid rounded-circle" src="{%static 'img/jean.jpg'%}" alt=""></a>              
                  </div>
                  <div class="media-body">
                      <span class="m-0"> <a href="">Jean Carlos Pedroso de França</a> </span>
                      <small><p><i class="icon ion-md-time"></i>Desenvolvedor</p></small>
                  </div>
              </div>
              <div class="card-body">
                <small class="card-text"><i style="padding: 5px;" class="bi bi-envelope"></i>Jeancarlossantos12@gmail.com</small>|
                <small class="card-text"><i style="padding: 5px;" class="bi bi-telephone-fill"></i>+55 (47) 9 9214-5877</small>
              </div>
            </div>
          </div>

        <div class="col mb-4">
            <div class="card">
              <div class="media m-0"  style="border-bottom: 1px solid #ccc; padding: 10px;">
                  <div class="d-flex mr-3">               
                      <a href="#"><img class="img-fluid rounded-circle" src="{%static 'img/luan.jpg'%}" alt=""></a>              
                  </div>
                  <div class="media-body">
                      <span class="m-0"> <a href="">Luan Gabriel Fausto Pereira</a> </span>
                      <small><p><i class="icon ion-md-time"></i>Desenvolvedor</p></small>
                  </div>
              </div>
              <div class="card-body">
                <small class="card-text"><i style="padding: 5px;" class="bi bi-envelope"></i>luangabrielfaustonobrac@gmail.com</small>|
                <small class="card-text"><i style="padding: 5px;" class="bi bi-telephone-fill"></i>+55 (47) 9 9154-3131</small>
              </div>
            </div>
          </div>

        <div class="col mb-4">
            <div class="card">
              <div class="media m-0"  style="border-bottom: 1px solid #ccc; padding: 10px;">
                  <div class="d-flex mr-3">               
                      <a href="#"><img class="img-fluid rounded-circle" src="{%static 'img/evanildo.jpg'%}" alt=""></a>              
                  </div>
                  <div class="media-body">
                      <span class="m-0"> <a href="">Evanildo Batista</a> </span>
                      <small><p><i class="icon ion-md-time"></i>Desenvolvedor</p></small>
                  </div>
              </div>
              <div class="card-body">
                <small class="card-text"><i style="padding: 5px;" class="bi bi-envelope"></i>niko.batista@hotmail.com</small>|
                <small class="card-text"><i style="padding: 5px;" class="bi bi-telephone-fill"></i>+55 (47) 9 9925-2598</small>
              </div>
            </div>
          </div>
        
      </div>
</div>





{%endblock%}

blog/Blog/templates/blog/home.html
{% extends "base.html" %} {% load static %} {% block title %}Infocode | Home{% endblock %} {% block main %}

<div class="container-sm text-center" style="margin-top: 15px">
    <!-- Alerta para rede social -->
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        Cadastre-se agora na nossa
        <a href="{% url 'usuarios:cadastro'%}"><strong>Rede Social</strong></a><span> ou </span><a href="{% url 'login' %}"><strong>Faça Login</strong></a>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    </div>
    <!-- Botões de indicação -->
    <div class="
    d-inline-flex
    list-group-horizontal-sm
      justify-content-center
    list-group
      btn-group
      categorias
      container-sm
    " role="group">

        {% for cat in categoria %}
        <form id="searchForm" class="
        categorias
        d-flex
        justify-content-center
        list-group list-group-horizontal
        align-items-center
        form-inline
      " action="" method="get">
            <ul class="list-group list-group-horizontal-sm align-items-center" style="display: inline-block">
                <li class="nav-link align-items-center">
                    <button type="submit" name="cat" role="group" value="{{cat}}" class="btn-group align-items-center btn-sm btn btn-outline-success">
            {{cat.categoria}}
          </button>
                </li>
            </ul>
        </form>
        {% endfor %}
        <!-- <li class="nav-link align-items-center">
            <a class="btn-sm btn btn-outline-success" href="{% url 'main:indicacao'%}">Indicações</a>
        </li> -->
    </div>
</div>

<!-- Loop para mostrar os posts -->
<div class="container-sm">
    {%for post in page_obj%}
    <div class="card mb-6" style="margin-top: 50px">
        <div class="row no-gutters">
            <div class="col-md-5">
                {% if post.foto %}
                <img class="img-fluid img-thumbnail posts" src="{{post.foto.url}}" alt="..." /> {%endif%}
            </div>
            <div class="col-md-7">
                <div class="card-body">
                    <h5 class="card-title font-weight-bold">{{post.titulo}}</h5>
                    {% if post.subtitulo %}
                    <p class="card-text font-weight-light">
                        <small>{{post.subtitulo|truncatewords:19|linebreaks}}</small>
                    </p>
                    {%endif%}
                    <p class="card-text">
                        {{post.conteúdo|truncatewords:20|linebreaks}}
                        <span><a href="{% url 'main:post_detail' post.id %}">Ver mais..</a></span>
                    </p>
                    <p class="card-text font-italic">
                        <small class="text-muted">Criado por {{post.criado_por}}, em {{post.criado_em}}</small>
                    </p>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

<!-- Páginação -->
<div class="pagination container-sm" style="margin-top: 25px; text-align: center">
    <div class="text-center">
        <p class="step-links align-items-center">
            {% if page_obj.has_previous %}
            <a class="text-center btn btn-outline-success" href="?page={{ page_obj.previous_page_number }}"><svg
          xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
          class="bi bi-arrow-left-circle-fill" viewBox="0 0 16 16">
          <path
            d="M8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0zm3.5 7.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z" />
        </svg></a> {% endif %}
            <span class="text-center btn current btn-outline-success">
        {{ page_obj.number }}
      </span> {% if page_obj.has_next %}
            <a class="btn-outline-success btn" href="?page={{ page_obj.next_page_number }}"><svg
          xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
          class="bi bi-arrow-right-circle-fill" viewBox="0 0 16 16">
          <path
            d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0zM4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H4.5z" />
        </svg></a> {% endif %}
        </p>
    </div>
</div>

<div class="container alert alert-success" role="alert">
    Temos algumas indicações de cursos e livros.
    <a href="{% url 'main:indicacao'%}"><strong>Confira aqui</strong></a>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
  <span aria-hidden="true">&times;</span>
</button>
</div>

<!-- Sobre os integrantes do projeto, feito independente do Django -->

<div class="container-lg align-items-center" id="sobre" style="margin-top: 45px; border-top: 1px solid #010139">
    <h1 class="text-center">INTEGRANTES DO PROJETO</h1>
    <div class="d-flex justify-content-center row align-self-center" style="margin-top: 15px; min-height: 350px">
        <!-- Card Antônio -->
        <div class="card col-sm align-items-center" style="width: 18rem; border: none">
            <img class="card-img-top" src="{% static 'img/antonio.jfif' %}" alt="Imagem de capa do card" style="width: 90px; height: 90px; border-radius: 50%" />
            <div class="card-body">
                <p class="card-text text-center font-italic">
                    "Minha experiência com a criação deste projeto foi incrível, pude colocar minhas habilidades em prática e aprimorar meus conhecimentos."
                </p>
                <h5 class="card-title text-center font-weight-light">
                    Antônio Bruno K. Lamim
                </h5>
                <p class="card-text text-center font-weight-light">Front-end</p>
                <div class="align-items-center">
                    <p class="text-center">
                        <a href="https://www.linkedin.com/in/ant%C3%B4nio-bruno-kremer-lamim/"><i class="bi bi-linkedin"></i></a>
                        <a href="https://github.com/BrunoKremer"><i class="bi bi-github"></i></a>
                    </p>
                </div>
                <!--svg-->
            </div>
            <!--Card-body-->
        </div>
        <!--Antonio - Card-->

        <!-- Card Evanildo -->
        <div class="card col-sm align-items-center" style="width: 18rem; border: none">
            <img class="card-img-top" src="{% static 'img/evanildo.jpg' %}" alt="Imagem de capa do card" style="width: 90px; height: 90px; border-radius: 50%" />
            <div class="card-body">
                <p class="card-text text-center font-italic">
                    "Esse projeto foi essencial para eu dar meus primeiros passos na area de programação, foi uma experiência muito gratificante que tive com essa equipe maravilhosa"
                </p>
                <h5 class="card-title text-center font-weight-light">
                    Evanildo Batista
                </h5>
                <p class="card-text text-center font-weight-light">Banco de Dados</p>
                <div class="align-items-center">
                    <p class="text-center">
                        <a href="https://www.linkedin.com/mwlite/in/evanildo-batista-94a46517b"><i class="bi bi-linkedin"></i></a>
                        <a href="https://github.com/Evanildo560"><i class="bi bi-github"></i></a>
                    </p>
                </div>
                <!--svg-->
            </div>
            <!--Card-body-->
        </div>
        <!--Evanildo - Card-->

        <!-- Card Jean -->
        <div class="card col-sm align-items-center" style="width: 18rem; border: none">
            <img class="card-img-top" src="{% static 'img/jean.jpg' %}" alt="Imagem de capa do card" style="width: 90px; height: 90px; border-radius: 50%" />
            <div class="card-body">
                <p class="card-text text-center font-italic">
                    "Com esse projeto, dei meus primeiros passos no mundo da programação, e foi fantástico poder se utilizar dessa troca de conhecimento com essa equipe incrível."
                </p>
                <h5 class="card-title text-center font-weight-light">
                    Jean Carlos P. França
                </h5>
                <p class="card-text text-center font-weight-light">Back-end e testes</p>
                <div class="align-items-center">
                    <p class="text-center">
                        <a href="https://www.linkedin.com/in/jean-fran%C3%A7a-a76567205"><i class="bi bi-linkedin"></i></a>
                        <a href="https://github.com/JeanFranca12"><i class="bi bi-github"></i></a>
                    </p>
                </div>
                <!--svg-->
            </div>
            <!--Card-body-->
        </div>
        <!--Jean - Card-->

        <!-- Card Luan -->
        <div class="card col-sm align-items-center" style="width: 18rem; border: none">
            <img class="card-img-top" src="{% static 'img/luan.jpg' %}" alt="Imagem de capa do card" style="width: 90px; height: 90px; border-radius: 50%" />
            <div class="card-body">
                <p class="card-text text-center font-italic">
                    "Com esse projeto, inicio na programação, pretendendo me profissionalizar ainda mais e obter cada vez mais conhecimento nessa área incrível que é a programação."
                </p>
                <h5 class="card-title text-center font-weight-light">
                    Luan Gabriel F. Pereira
                </h5>
                <p class="card-text text-center font-weight-light">
                    Documentação e Conteúdo
                </p>
                <div class="align-items-center">
                    <p class="text-center">
                        <a href="https://www.linkedin.com/in/luan-gabriel-56aa28207"><i class="bi bi-linkedin"></i></a>
                        <a href="https://github.com/VolkLuan"><i class="bi bi-github"></i></a>
                    </p>
                </div>
                <!--svg-->
            </div>
            <!--Card-body-->
        </div>
        <!--Luan - Card-->
    </div>
</div>
  
{% endblock %}

blog/Blog/templates/blog/indicacao.html
 {% extends "base.html" %} {% load crispy_forms_tags %} {% load static %} {% block title %}Infocode | Indicações{% endblock %} {% block main %}

<div class="container-sm">
    <h2 class="text-center">Indicações</h2>

    <!-- Slide de indicações -->
    <article class="c-carousel c-carousel--responsive align-items-center text-center" style=" margin-top: 75px;">
        <div class="c-carousel__slides js-carousel--responsive ">
            {%for ind in indicacao %}

            <article class="c-carousel__slide align-items-center" style="padding: 20px;" >
                <div class="card" style="width: 25rem; min-height: 38rem; max-height: 38rem;">
                    <img src="{{ind.foto.url}}" class="img-fluid img-thumbnail card-img-top" alt="..." style="min-height: 20rem; max-height: 20px;">
                    <div class="card-body">
                        <h5 class="card-title">{{ind.titulo}}</h5>
                        <p class="card-text">{{ind.categoria}}</p>
                        <a href="{% url 'main:indicacao_detail' ind.id %}" class="btn btn-outline-success">Ver mais</a>
                    </div>
                </div>
            </article>
            {%endfor%}
        </div>
        <button class="js-carousel--responsive-prev btn" aria-label="Anterior">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left-circle-fill" viewBox="0 0 16 16">
        <path d="M8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0zm3.5 7.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/>
      </svg>
  </button>

        <button class="js-carousel--responsive-next btn" aria-label="Próximo">
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-right-circle-fill" viewBox="0 0 16 16">
        <path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0zM4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H4.5z"/>
      </svg>
  </button>
        <div class="js-carousel--responsive-dots" role="tablist"></div>
    </article>

</div>





{% endblock %}

blog/Blog/templates/blog/indicacao_detail.html
{% extends "base.html" %} {% load crispy_forms_tags %} {% load static %} {% block title %}Infocode | Indicações | {{indicacao.titulo}}{% endblock %} {% block main %}
<!-- Indicação -->
<div class="container">
    <h1 class="text-center" style="margin-top: 25px;">{{indicacao.titulo}}</h1>
    <div class="row" style="margin-top: 25px; padding: 5%;">
        <div class="">
            {% if indicacao.foto %}
            <img src="{{indicacao.foto.url}}" class="img-fluid img-thumbnail" alt="" srcset="" style="margin-top: 20px;" > {%endif%}
        </div>
        <div class="">
            <p class="card-text">{{indicacao.sinopse|linebreaks}}</p>
            <p class="card-text">Autor: {{indicacao.autor}}</p>
            <p class="card-text">Você pode adquirir <a class="stretched-link text-success" href="{{indicacao.link}}">clicando aqui  </a></p>
        </div>
    </div>
</div>
{% endblock %} {% block content %} {% endblock %}

blog/Blog/templates/blog/post_detail.html
{% extends "base.html" %} {% load crispy_forms_tags %} {% load static %} {% block title %}{{post.titulo}}{% endblock %} {% block main %}
<!-- Post -->
<div class="container">
    <h1 class="text-center">{{post.titulo}}</h1>
    {% if post.subtitulo %}
    <h6 class="text-center">{{post.subtitulo}}</h6>
    {%endif%} {% if post.foto %}
    <img src="{{post.foto.url}}" class='img-fluid img-thumbnail' alt="" srcset="" > {%endif%}

    <p class="card-text">{{post.conteúdo|linebreaks}}</p>
</div>
{% endblock %} {%block content%} {% if request.user.is_authenticated %}
<div class="container">
    <form action="{% url 'main:curtir_post' %}" method='POST'>
        {% csrf_token %}
        <input type="hidden" name="post_id" value="{{post.id}}"> {% if user not in post.curtidas.all %}
        <a href=""><button  class="btn btn-outline-success " type="submit"><i class="bi bi-heart"></i></button></a> {% else %}
        <a href=""><button type="submit" class=" btn-group align-items-center btn-sm btn btn-outline-success">Não Gostei</button></a> {% endif %}
    </form>
    <strong>{{post.curtidas.all.count}} Curtida{{post.curtidas.all.count|pluralize:"s"}} </strong>
</div>
<!-- Form de Comentário -->
<div class="container">
    <h1>Faça um comentário</h1>
    <form method="POST">
        {% csrf_token %}
        <div class="form-row">
            <div class="form-group col-md-8">
                {{ form.comentario|as_crispy_field }}
            </div>
        </div>
        <p><input class="btn btn-success" type="submit" value="Salvar"></p>
    </form>
</div>
{% endif %}
{% for review in post.reviews_set.all %}
<div class="comment__details container"  style="margin-bottom: 10px;">
    <div class="card card-body" style="height: 140px;">
        <div class="cardbox-heading">

            <div class="media m-0">

                
                <div class="media-body">
                    <span class="m-0"> <a href="{% url 'usuarios:profile' review.usuario.id%}">{{review.usuario}}</a> </span>
                    <small><p><i class="icon ion-md-time"></i>{{review.criacao}}</p></small>
                </div>

            </div>
            <!--/ media -->
        </div>
        <!--/ cardbox-heading -->
        <div class="cardbox-item">
            <p class="card-text">{{review.comentario|linebreaks}} </p>
        </div>
        <!--/ cardbox-item -->


    </div>
    <!--card-->
</div>
<!--collapse-->
{% endfor %}

<!-- Comentarios -->





<div class="container" style="margin-top: 25px;">
    <i class="fa fa-google"></i>
    <a class="btn btn-success" href="{% url 'social-auth:begin' 'google-oauth2' %}">
        Login com Google
     </a>


    <i class="fa fa-facebook"></i>
    <a class="btn btn-success" href="{% url 'social-auth:begin' 'facebook' %}">
        Login com Facebook
    </a>

</div>

{%endblock%}