blog/Blog/Blog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token
from main.api import viewsets

router = routers.DefaultRouter()
router.register(r'blog', viewsets.PostViewSet)
router.register(r'category', viewsets.CategoriaViewSet)
router.register(r'indicacao', viewsets.IndicacaoViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/', include(router.urls)),
    path('api-token-auth/', obtain_auth_token),
    path('', include('main.urls', namespace = 'main')),
    path('user/', include('usuarios.urls', namespace = 'usuarios')),
    path('social/', include('social.urls', namespace = 'social')),
    path('social-auth/', include('social_django.urls', namespace='social-auth')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)


admin.site.site_header = 'Infocode'
admin.site.site_title = 'Mantenha-se conectado com todas tecnologias'
admin.site.site_header = 'Sistema de gerenciamento da infocode'

blog/Blog/main/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from django.views.static import serve

from django.urls import path, include
from . import views
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

app_name = 'main'

urlpatterns = [
    # Url principal do blog
    path('', views.home, name = 'post'),
    # Url que redireciona para um artigo especificio pelo ID
    path('<int:pk>/', views.PostDetailView, name='post_detail'),
    # Url que redireciona para nossas indicações de livros e cursos
    path('indicacao/', views.indicacao, name='indicacao'),
    # Url que redireciona para uma indicação especificia pelo ID
    path('indicacao/<int:pk>/', views.IndicacaoDetailView.as_view(), name='indicacao_detail'),
    path('contato', views.Contato_view.as_view(), name='contato'),

    path('curtir/', views.curtir_post, name='curtir_post'),
]

blog/Blog/social/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from django.views.static import serve

from django.urls import path, include
from . import views
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

app_name = 'social'

urlpatterns = [
    # Url do Feed, onde mostra todas publicações feitas
    path('feed', views.feed, name='feed'), 
    # Url para deletar POST escolhido pelo usuário, utilizamos a ID para fazer a seleção do POST
    path('deletar-post/<str:id>/', views.deletarPublicacao, name='deletar-post'),
    # Url para editar POST escolhido pelo usuário
    path('editar-post/<str:id>/', views.editarPublicacao, name='editar-post'),
    # Url para comentar POST escolhido pelo usuário
    path('comentar_post/<str:id>/', views.comentar_Publicacao, name='comentar_post'),
    # Url para ver POST completo(comentários) escolhido pelo usuário
    path('usuarios/', views.usuarios, name='usuarios'),

    path('like/', views.like_post, name='like_post'),
    
]

blog/Blog/usuarios/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from django.views.static import serve

from django.urls import path, include
from . import views
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

app_name = 'usuarios'

urlpatterns = [
    # View com formulário de cadastro de usuários
    path('cadastro', views.CadastroFormView.as_view(), name='cadastro'),
    # View que redireciona após o sucesso de cadastro
    path('cadastro/sucess', views.RegistradoView.as_view(), name='sucess'),
    # View de perfil do usuário
    path('profile/<int:pk>', views.ProfileView, name='profile'),  
    # View para editar informações de usuários
    path('edit/<int:pk>', views.UserChange.as_view(), name='edit'),

    path('seguir/<int:id>', views.seguir_usuario, name = 'seguir')

]           

blog/Blog/templates/base.html
{% load static %} {% load crispy_forms_tags %}


<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit = no">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://fonts.googleapis.com/css?family=Nunito:400,800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/glider-js@1/glider.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/logo.ico' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type='text/css'>
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-light " style="background-color: #8fc38a;">
        <div class="container-sm">
            <div>
                <a href="/"><img src=" {% static 'img/logo.png'%}" alt="image" srcset="" style="width: 40px;"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            </div>
            <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                <form id="searchForm" class="form text-left  form-inline" action="" method="get">
                    <div class="form__field form-group">
                        <input class="input input--text form-control-sm" id="formInput#search" type="text" name="cat" value="{{cat}}" placeholder="Pesquisar..." style="border: none;" />
                        <button class="btn">
                            <i class="bi bi-search"></i>
                        </button>
                    </div>
                </form>
                <ul class="navbar-nav link-menu navbar-nav-scroll">
                    <li class="nav-item active">
                        <a class="nav-link  " href="/"><i class="bi bi-house-fill"></i><span class="sr-only ">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="#sobre"><i class="bi bi-person-square"></i><span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{%url 'main:contato'%}"><i class="bi bi-telephone-fill"></i><span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                        <a title="Quem somos" class="nav-link" target="blank" href="https://github.com/BrunoKremer/g3-rede-social-blog/blob/main/README.md"><i class="bi bi-question-square-fill"></i></i><span class="sr-only">(current)</span></a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <section>
        <div class="text-center">
            <img class="img-fluid" src="{% static 'img/banner.png'%}" alt="banner" srcset="" style="height: 150px; margin-top: 50px;">
        </div>
    </section>

    {% block main %} {% endblock %} {% block content %} {% endblock %} {% include 'snipetts/rodape.html' %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/glider-js@1/glider.min.js"></script>
    <script src="{% static 'js/index.js' %}"></script>
</body>

</html>

blog/Blog/templates/base_accounts.html
{% load static %} {% load crispy_forms_tags %}


<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit = no">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:400,800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/glider-js@1/glider.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/logo.ico' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type='text/css'>
</head>


<body style="background-color: #d9ffe3;">

    <section>
        <div class="text-center">
            <img class="img-fluid" src="{% static 'img/banner.png'%}" alt="banner" srcset="" style="height: 150px; margin-top: 50px;">
        </div>
    </section>








    {% block main %} {% endblock %} {% block content %} {% endblock %}


    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/glider-js@1/glider.min.js"></script>
    <script src="{% static 'js/index.js' %}"></script>
</body>

</html>

blog/Blog/templates/base_social.html
{% load static %} {% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}Feed{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css" />
    <link href="https://fonts.googleapis.com/css?family=Nunito:400,800&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/glider-js@1/glider.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css" />
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/logo.ico' %}" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" />
</head>

<body style="background-color: #deffdb">
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #8fc38a">
        <div class="container-sm">
            <div>
                <a href="/"><img src=" {% static 'img/logo.png'%}" alt="image" srcset="" style="width: 40px" /></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
            </div>
            <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                <form id="searchForm" class="form text-left form-inline" action="" method="get">
                    <div class="form__field form-group">
                        <input class="input input--text form-control-sm" id="formInput#search" type="text" name="cat" value="{{cat}}" placeholder="Pesquisar..." style="border: none" />
                        <button class="btn">
                <i class="bi bi-search"></i>
              </button>
                    </div>
                </form>
                <ul class="navbar-nav link-menu navbar-nav-scroll">
                    <li class="nav-item active">
                        <a title="feed" class="nav-link" href="{% url 'social:feed'%}"><i class="bi bi-house-fill"></i
                ><span class="sr-only">(current)</span></a
              >
            </li>
            <li class="nav-item active">
              <a title="{{request.user.get_full_name}}" class="nav-link" href="{% url 'usuarios:profile' user.id%}"
                ><i class="bi bi-person-square"></i
                ><span class="sr-only">(current)</span></a
              >
            </li>
            <li class="nav-item active">

              <div class="btn-group dropleft">
               <a title="menu" style="margin-top: 8px;" role="button" data-toggle="dropdown"  class=" dropdown-toggle"><i class="bi bi-menu-button-wide"></i></a>
                  
                
                <div class="dropdown-menu">
                  <a title="Logout" class="dropdown-item" href="{%url 'logout'%}"><i class="bi bi-box-arrow-right"></i></a>
                  <a title="Encontre pessoas" class="dropdown-item" href="{%url 'social:usuarios'%}"><i class="bi bi-people-fill"></i></a>
                </div>
              </div>

              
            </li>
          </ul>
        </div>
      </div>
    </nav>

    




  {%block main%} {%endblock%}

    
    {%block content%} {%endblock%}

    

    <script
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
      integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"
      integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF"
      crossorigin="anonymous"
    ></script>
    <script src="https://cdn.jsdelivr.net/npm/glider-js@1/glider.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{% static 'js/index.js' %}"></script>
  </body>
</html>